GET http://localhost:3000/bank-accounts
###

GET http://localhost:3000/bank-accounts/C12346A
###

POST http://localhost:3000/bank-accounts
Content-Type: application/json

{
  "account_number": "C12346A"
}
###

PATCH  http://localhost:3000/bank-accounts/123
Content-Type: application/json

{
  "account_number": "C12346A"
}
###

DELETE  http://localhost:3000/bank-accounts/123
###

POST http://localhost:3000/bank-accounts/transfer
Content-Type: application/json

{
  "from": "C12346A",
  "to": "B45134C",
  "amount": 100
}
###